version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $REPO_DOMAIN
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_DOMAIN
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file... $NAME_REPOSITORY
      - printf '[{"name":"%s","imageUri":"%s"}]' "$NAME_REPOSITORY" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
    files: imagedefinitions.json