version: '3.8'
services:
  portalDataBase:
    image: mysql:8.0
    container_name: portal_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal
    ports:
      - "3306:3306"