AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create a MySQL database in Amazon RDS"

Resources:
  MyDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: "db.t3.micro"
      AllocatedStorage: "20"
      DBName: "portal"
      Engine: "MySQL"
      MasterUsername: "majerhua"
      MasterUserPassword: "majerhua123"
      VPCSecurityGroups:
        - !GetAtt MyDBSecurityGroup.GroupId
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: true

  MyDBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable access to the database"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: "0.0.0.0/0"
